### PR TITLE
Implement OpenID Connect Discovery

### LINKED ISSUE #22: Support OpenID Connect Discovery to pull in endpoint urls and keysets
All OpenID Connect standard compliant servers implement .well-known endpoints for discovering underlying endpoint urls and public keys (multiple for issues like rotation)

The complexity is in converting the keysets from JWK format to PEM

provider configuration would then be at the minimum:

* issuerUrl - The url of the IdP, which underneath sits .well-known/openid-configuration
* clientId - (if authenticating, not required for validation if allowedAudience supplied)
* clientSecret - (if the IdP server requires it for authenticating)
* allowedAudience - (optional for validation, matching either the string aud claim, or if aud claim is an array, one of the array entries)

### PR DESCRIPTION
**Pull request by FWest98**
This PR implements support for automatic discovery of OpenID Connect configuration, as specified [here](https://openid.net/specs/openid-connect-discovery-1_0.html).

Fixes #22 

Details: adds an `issuer` configuration field, which, when present, will cause the provider to dynamically set all other options based on the data at the `<issuer>/.well-known/openid-configuration` endpoint. This includes public key configuration.

### CODE REVIEW

**Comment by steverhoades** [comment]
@FWest98 Thank you for the PR, I apologize for the delay in the review. If it's not too much trouble can you add some documentation to the Readme? Once that is done it looks good to me.

**Comment by FWest98** [comment]
Well.. For an entire year I was thinking you asked for unit tests instead of documentation..... But now I decided to add both and finally update the MR!

**Comment by rafaelklaessen** [comment]
@steverhoades @FWest98 What's the status of this MR? :)

**Comment by FWest98** [comment]
As far as I'm concerned, this is ready to merge, but I guess by now there are merge conflicts. I will try to fix those in the coming days

**Comment by FWest98** [comment]
Please refer to #37

**Pull request closed without merging**
